- hosts: webserver
  become: yes
  tasks:
  - name: Instalando o Apache
    package:
      name: ['apache2']
      state: present
  - name: Garantindo inicialização do Apache
    service:
      name: apache2
      state: started
      enabled: yes
  - name: Garantindo site
    copy:
      src: site/
      dest: /var/www/html
